import { GetStaticProps } from 'next';
import Head from 'next/head';

import { useTranslation } from 'next-i18next';
import { loadTranslation } from '../util/translations';

import { Header } from '../components/Header';

export default function Contact() {
  const { t } = useTranslation('contact');

  return (
    <div>
      <Head>
        <title>{t("title")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <h1>{t("title")}</h1>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await loadTranslation(locale!, ['contact'])),
    },
  };
}