import { useState } from 'react';
import { GetStaticProps } from 'next';
import Head from 'next/head'
import Link from 'next/link';

import { useTranslation } from 'next-i18next';
import { loadTranslation } from '../util/translations';

import { Header } from '../components/Header';

export default function Home() {
  const [messagesCounter, setMessagesCounter] = useState(0);
  const { t } = useTranslation('home');

  return (
    <div>
      <Head>
        <title>{t("title")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <h1>{t("title")}</h1>
      <h3>{t("description")}</h3>

      <p>
        {t("unreadMessages", {
          count: messagesCounter,
        })}
      </p>

      <button onClick={() => setMessagesCounter((previousState) => previousState + 1)}>+</button>
      <button onClick={() => setMessagesCounter((previousState) => previousState - 1)}>-</button>

      <Link href="/contact">
        {t("contactLink")}
      </Link>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await loadTranslation(locale!, ['home'])),
    },
  };
}